### IMPORTING LIBRARIES

In [56]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

### LOADING DATA SET

In [57]:
# Load your dataset
df = pd.read_csv('NFL Play by Play 2009-2016 (v3).csv')

C:\Users\DE\AppData\Local\Temp\ipykernel_10424\1870917626.py:2: DtypeWarning: Columns (25,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('NFL Play by Play 2009-2016 (v3).csv')


### LABEL ENCODING

In [58]:
from sklearn.preprocessing import LabelEncoder

# Create an instance of the LabelEncoder
label_encoder = LabelEncoder()

# Iterate through all columns in the DataFrame
for column in df.columns:
    if df[column].dtype == 'object':  # Check if the column contains string values
        df[column] = label_encoder.fit_transform(df[column])

# Now, all columns with string values have been label encoded in the DataFrame

### LIST OF COLUMNS

In [59]:
df.columns.tolist()

['Date',
 'GameID',
 'Drive',
 'qtr',
 'down',
 'time',
 'TimeUnder',
 'TimeSecs',
 'PlayTimeDiff',
 'SideofField',
 'yrdln',
 'yrdline100',
 'ydstogo',
 'ydsnet',
 'GoalToGo',
 'FirstDown',
 'posteam',
 'DefensiveTeam',
 'desc',
 'PlayAttempted',
 'Yards.Gained',
 'sp',
 'Touchdown',
 'ExPointResult',
 'TwoPointConv',
 'DefTwoPoint',
 'Safety',
 'Onsidekick',
 'PuntResult',
 'PlayType',
 'Passer',
 'Passer_ID',
 'PassAttempt',
 'PassOutcome',
 'PassLength',
 'AirYards',
 'YardsAfterCatch',
 'QBHit',
 'PassLocation',
 'InterceptionThrown',
 'Interceptor',
 'Rusher',
 'Rusher_ID',
 'RushAttempt',
 'RunLocation',
 'RunGap',
 'Receiver',
 'Receiver_ID',
 'Reception',
 'ReturnResult',
 'Returner',
 'BlockingPlayer',
 'Tackler1',
 'Tackler2',
 'FieldGoalResult',
 'FieldGoalDistance',
 'Fumble',
 'RecFumbTeam',
 'RecFumbPlayer',
 'Sack',
 'Challenge.Replay',
 'ChalReplayResult',
 'Accepted.Penalty',
 'PenalizedTeam',
 'PenaltyType',
 'PenalizedPlayer',
 'Penalty.Yards',
 'PosTeamScore',
 'De

In [60]:
df.shape

(362447, 102)

### STRING COLUMNS

In [61]:

# Identify columns with string values for label encoding
string_columns = df.select_dtypes(include=['object']).columns
string_columns

Index([], dtype='object')

In [62]:
# Create an instance of the LabelEncoder
label_encoder = LabelEncoder()

In [63]:
# Apply label encoding to string columns
for column in string_columns:
    df[column] = label_encoder.fit_transform(df[column])

### YARD.GAINED

In [64]:
# Define the target variable and features
Y = df['Yards.Gained']
X = df.drop(['Yards.Gained'], axis=1)

### TRAIN & TEST

In [65]:
# Split the dataset into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [66]:
len(Y_train)

289957

In [67]:
len(Y_test)

72490

In [68]:
len(X_train)

289957

In [69]:
len(X_test)

72490

In [70]:
missing_values = X_train.isna().sum()
missing_values

Date             0
GameID           0
Drive            0
qtr              0
down         43364
             ...  
Win_Prob     17626
WPA           3837
airWPA      176560
yacWPA      176725
Season           0
Length: 101, dtype: int64

### Replacing NaN values

In [71]:
X_train.fillna(X_train.mean(), inplace=True)  # Replace NaN with the mean of the column

### APPLIED REGRESSION

In [72]:

# Initialize and train a linear regression model
regression_model = LinearRegression()
regression_model.fit(X_train, Y_train)

LinearRegression()

In [73]:
len(X_train)

289957

In [74]:
len(X_test)

72490

### Total Missing Values

In [75]:
missing_values = X_train.isna().sum()
missing_values

Date        0
GameID      0
Drive       0
qtr         0
down        0
           ..
Win_Prob    0
WPA         0
airWPA      0
yacWPA      0
Season      0
Length: 101, dtype: int64

In [76]:
X_train.fillna(X_train.mean(), inplace=True)  # Replace NaN with the mean of the column

In [77]:
missing_values

Date        0
GameID      0
Drive       0
qtr         0
down        0
           ..
Win_Prob    0
WPA         0
airWPA      0
yacWPA      0
Season      0
Length: 101, dtype: int64

In [78]:
# Handle missing values in X_test using the same method you used for X_train
X_test.fillna(X_train.mean(), inplace=True)  # Replace NaN with the mean of the column

## Test

In [79]:

# Make predictions on the test set
Y_pred = regression_model.predict(X_test)
Y_pred

array([-0.91951612, -1.53220175,  7.90771706, ..., 11.84974706,
       -0.16114066,  5.08798048])

In [80]:
from sklearn.linear_model import LinearRegression

In [81]:
clf = LinearRegression()

In [82]:
clf.fit(X_train, Y_train)

LinearRegression()

In [83]:
clf.predict(X_test)

array([-0.91951612, -1.53220175,  7.90771706, ..., 11.84974706,
       -0.16114066,  5.08798048])

In [84]:
Y_test

128550     0
133422     0
343058     5
56448      3
224000     1
          ..
110712     9
57468     14
208503     8
353763     0
48187      2
Name: Yards.Gained, Length: 72490, dtype: int64

## Accuracy

In [85]:
clf.score(X_test, Y_test)

0.6436871365284054

In [86]:
# Evaluate the regression model
mse = mean_squared_error(Y_test, Y_pred)
r2 = r2_score(Y_test, Y_pred)

### ACCURACY

In [87]:
# Print evaluation metrics
print("Mean Squared Error (MSE):", mse)
print("R-squared (R2) Score:", r2)

Mean Squared Error (MSE): 29.80253220711799
R-squared (R2) Score: 0.6436871365284054


ACHIVED 64% ACCURACY FROM THIS DATASET

### Performed same with other regressor types

In [88]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [89]:
# Load the dataset (replace 'your_file.csv' with the actual file name)
file_path = 'NFL Play by Play 2009-2016 (v3).csv'
data = pd.read_csv(file_path)

C:\Users\DE\AppData\Local\Temp\ipykernel_10424\92971808.py:3: DtypeWarning: Columns (25,51) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(file_path)


In [90]:
# Identify columns with string values for label encoding
string_columns = data.select_dtypes(include=['object']).columns

In [91]:
# Create label encoders for each string column
label_encoders = {}
for col in string_columns:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    label_encoders[col] = le


In [92]:
# Split the data into training and testing sets
X = data.drop(columns=['Yards.Gained'])  # Features
y = data['Yards.Gained']  # Target variable

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [93]:
X_train.fillna(X_train.mean(), inplace=True)  # Replace NaN with the mean of the column

In [94]:
# Handle missing values in X_test using the same method you used for X_train
X_test.fillna(X_train.mean(), inplace=True)  # Replace NaN with the mean of the column

### Linear Regression

In [95]:
# Perform Linear Regression
linear_regressor = LinearRegression()
linear_regressor.fit(X_train, y_train)
linear_y_pred = linear_regressor.predict(X_test)
linear_y_pred

array([-0.91951612, -1.53220175,  7.90771706, ..., 11.84974706,
       -0.16114066,  5.08798048])

### Descision Tree Regression

In [96]:
# Perform Decision Tree Regression
decision_tree_regressor = DecisionTreeRegressor(random_state=42)
decision_tree_regressor.fit(X_train, y_train)
dt_y_pred = decision_tree_regressor.predict(X_test)
dt_y_pred

array([0., 0., 5., ..., 4., 0., 2.])

In [97]:
# Evaluate the regression model
mse = mean_squared_error(Y_test, Y_pred)
r2 = r2_score(Y_test, Y_pred)

In [98]:
### ACCURACY
# Print evaluation metrics
print("Mean Squared Error (MSE):", mse)
print("R-squared (R2) Score:", r2)

Mean Squared Error (MSE): 29.80253220711799
R-squared (R2) Score: 0.6436871365284054


### Random Forest

In [99]:
# Select features and target variable
X = data.drop(columns=['Yards.Gained'])  # Features
y = data['Yards.Gained']  # Target variable

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a Random Forest Regressor
regressor = RandomForestRegressor(n_estimators=100, max_depth=10, random_state=42)

# Train the model
regressor.fit(X_train, y_train)

# Make predictions on the test set
y_pred = regressor.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")


ValueError: Input X contains NaN.
RandomForestRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
pip install xgboost

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Python310\python.exe -m pip install --upgrade pip' command.


In [ ]:
import xgboost as xgb

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import xgboost as xgb
from sklearn.metrics import mean_squared_error, r2_score


In [ ]:
# Load the dataset (replace 'your_file.csv' with the actual file name)
file_path = 'NFL Play by Play 2009-2016 (v3).csv'
data = pd.read_csv(file_path)

# Identify columns with string values for label encoding
string_columns = data.select_dtypes(include=['object']).columns

# Create label encoders for each string column
label_encoders = {}
for col in string_columns:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    label_encoders[col] = le

C:\Users\DE\AppData\Local\Temp\ipykernel_7932\2271482405.py:3: DtypeWarning: Columns (25,51) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(file_path)


In [ ]:
# Split the data into training and testing sets
X = data.drop(columns=['Yards.Gained'])  # Features
y = data['Yards.Gained']  # Target variable

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Handle missing values in X_train using the same method you used before
X_train.fillna(X_train.mean(), inplace=True)

# Handle missing values in X_test using the same method you used for X_train
X_test.fillna(X_train.mean(), inplace=True)

In [ ]:
# Initialize and train the XGBoost regression model
xgboost_regressor = xgb.XGBRegressor()
xgboost_regressor.fit(X_train, y_train)

c:\Python310\lib\site-packages\xgboost\data.py:312: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
c:\Python310\lib\site-packages\xgboost\data.py:314: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  elif is_categorical_dtype(dtype) and enable_categorical:
c:\Python310\lib\site-packages\xgboost\data.py:345: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype)
c:\Python310\lib\site-packages\xgboost\data.py:336: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  return is_int or is_bool or is_float or is_categorical_dtype(dtype)
c:\Python310\lib\site-packages\xgboost\data.py:440: FutureW

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=100, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [ ]:

# Make predictions on the test set
xgboost_y_pred = xgboost_regressor.predict(X_test)

c:\Python310\lib\site-packages\xgboost\data.py:312: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
c:\Python310\lib\site-packages\xgboost\data.py:314: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  elif is_categorical_dtype(dtype) and enable_categorical:
c:\Python310\lib\site-packages\xgboost\data.py:345: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype)
c:\Python310\lib\site-packages\xgboost\data.py:336: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  return is_int or is_bool or is_float or is_categorical_dtype(dtype)


In [ ]:

# Evaluate the regression model
mse = mean_squared_error(y_test, xgboost_y_pred)
r2 = r2_score(y_test, xgboost_y_pred)

In [ ]:
# Print evaluation metrics
print("XGBoost Mean Squared Error (MSE):", mse)
print("XGBoost R-squared (R2) Score:", r2)

XGBoost Mean Squared Error (MSE): 6.942765430678572
XGBoost R-squared (R2) Score: 0.9169937435576081


In [ ]:
# Replace Decision Tree Regression with XGBoost Regression
xgb_regressor = xgb.XGBRegressor(random_state=42)
xgb_regressor.fit(X_train, y_train)
xgb_y_pred = xgb_regressor.predict(X_test)

In [ ]:
# Replace Random Forest Regression with XGBoost Regression
xgb_regressor = xgb.XGBRegressor(n_estimators=100, random_state=42)
xgb_regressor.fit(X_train, y_train)
xgb_y_pred = xgb_regressor.predict(X_test)

In [ ]:
# Evaluate the XGBoost model
mse = mean_squared_error(y_test, xgb_y_pred)
r2 = r2_score(y_test, xgb_y_pred)

# Print evaluation metrics
print("XGBoost Mean Squared Error (MSE):", mse)
print("XGBoost R-squared (R2) Score:", r2)

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Generate some sample data
np.random.seed(42)
X = data.drop(columns=['Yards.Gained'])  # Features
y = data['Yards.Gained']  # Target variable

In [ ]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



In [101]:
# Handle missing values in X_train using the same method you used before
X_train.fillna(X_train.mean(), inplace=True)

# Handle missing values in X_test using the same method you used for X_train
X_test.fillna(X_train.mean(), inplace=True)

In [102]:
# Create and train a linear regression model
regressor = LinearRegression()
regressor.fit(X_train, y_train)

# Make predictions on the test set
y_pred = regressor.predict(X_test)


In [105]:
Y_test_series = y_test.reset_index(drop=True)
Y_pred_series = pd.Series(y_pred)
df_results = pd.DataFrame({'Yards.Gained_Y_test': Y_test_series, 'Yards.Gained_Y_pred': Y_pred_series})
df_results.head(20)

Yards.Gained_Y_test  Yards.Gained_Y_pred
0                     0            -0.919516
1                     0            -1.532202
2                     5             7.907717
3                     3             4.083317
4                     1             0.380969
5                    11             8.950399
6                     0            -1.156932
7                     0            -1.609530
8                     3             2.700173
9                     2             2.104894
10                   11            12.832269
11                   15            22.901359
12                    1             6.546292
13                    0            -1.715841
14                    0             2.957817
15                   10             7.134729
16                    5             3.391909
17                    3             3.135550
18                   29            22.154765
19                   -1             2.797899

In [ ]:
# Evaluate the model's performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [ ]:
print("Predicted Values (y_pred):")
print(y_pred[:5])  # Print the first 5 predicted values

Predicted Values (y_pred):
[-0.91951612 -1.53220175  7.90771706  4.08331695  0.38096907]


In [ ]:

print("\nActual Target Values (y_test):")
print(y_test[:5])  # Print the first 5 actual target values


Actual Target Values (y_test):
128550    0
133422    0
343058    5
56448     3
224000    1
Name: Yards.Gained, dtype: int64


In [ ]:
print(f"\nMean Squared Error: {mse}")
print(f"R-squared: {r2}")


Mean Squared Error: 29.80253220711799
R-squared: 0.6436871365284054


In [ ]:
import pandas as pd

# Create dataframes for y_pred and y_test
y_pred_df = pd.DataFrame({'Predicted Values (y_pred)': y_pred})
y_test_df = pd.DataFrame({'Actual Target Values (y_test)': y_test})

# Display the first 5 rows of each dataframe
print("Predicted Values (y_pred):")
y_pred_df.head(5)


Predicted Values (y_pred):


Predicted Values (y_pred)
0                  -0.919516
1                  -1.532202
2                   7.907717
3                   4.083317
4                   0.380969

In [ ]:
print("\nActual Target Values (y_test):")
y_test_df.head(5)


Actual Target Values (y_test):


Actual Target Values (y_test)
128550                              0
133422                              0
343058                              5
56448                               3
224000                              1

In [ ]:
Y_test_series = y_test.reset_index(drop=True)
Y_pred_series = pd.Series(y_pred)
df_results = pd.DataFrame({'Yards.Gained_Y_test': Y_test_series, 'Yards.Gained_Y_pred': Y_pred_series})

NameError: name 'y_pred' is not defined